[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "inla"
requires-python = ">=3.8"
version = "0.1.0"
description = "Fast approximate Bayesian inference using INLA, written in Rust"
license = "Apache-2.0"
urls = { Repository = "https://github.com/tenderking/rust-inla" }
dependencies = ["numpy", "scipy"]

[project.optional-dependencies]
dev = ["pytest", "pandas"]

[tool.maturin]
python-source = "python"
module-name = "inla._native"
